# Generated by Django 3.1.3 on 2020-11-25 15:19

import django.utils.timezone
from django.db import migrations, models

import idvalidator.validators


class Migration(migrations.Migration):
    dependencies = [
        ('idvalidator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='business_id',
            field=models.CharField(max_length=8, validators=[idvalidator.validators.validate_business_id]),
        ),
    ]
